### ISSUE TITLE
PHP 7.1 released

### ISSUE THREAD

**Issue by ruudk** [circleci/image-builder#119]
http://php.net/archive/2016.php#id2016-12-01-3

**Comment by kimh** [comment]
Sorry for late response.

I can't pre-install php 7.1 in the container but I went ahead and created the package which mitigates the pain of installing the version in every build. You can do something like this:

https://circleci.com/gh/kimh/trusty-test/661#config/containers/0

```
machine:
  pre:
    - sudo apt-get update; USE_PRECOMPILE=true sudo -E circleci-install php 7.1.0

  php:
    version: 7.1.0

dependencies:
  override:
    - exit 0

test:
  override:
    - php --version
```

We'll be installing the version in the next image update. I'll close this issue for now but please feel free reopen if you have any issues.

Thanks!
